
structure = [] # path to structure file or files
input_type = "sdf" # accepts sdf, smarts, smiles, inchi
nmr_file = "" # path to nmr data or a folder
stereocentres = [] # stereocentres to alter

solvent = ""

log_level = "info"
log_file = ""

output_folder = "" # uses current working directory by default
gui_running = false # will work with GUI


[workflow]
cleanup = false # c RDkit cleaning of input structures and 3d coordinate generation
generate = true # g generate diastereomers
conf_search = true # m Run conformational search.
dft_energies = true # e DFT single point energies. Useful for accurate conformer ranking.
dft_opt = true # o  DFT optimisation of structures. Useful for precise geometries.
dft_nmr = true # n DFT shielding tensor calculation. Must be later transformed into NMR shifts.
dp4 = true # s perform DP4 analysis based on computed and experimental data
dp5 = true # w perform DP4 analysis based on computed and experimental data
assign_only = false # a perform assignment only

calculations_complete = false
optimisation_converged = false
restart_dft = false

mm_complete = false
dft_complete = false


[conformer_search]
method = "macromodel" # accepts "macromodel", "tinker", "etkdg"
force_field = "mmff"
step_count = 10000 # maximum number of steps overall
steps_per_rotatable_bond = 2500 # maximum number of steps per rotatable bond
manual_five_membered_rings = false # manually alter five-membered rings by FiveConf.py
five_membered_ring_atoms = [] # specify atoms in 5-membered rings of interest

conf_prune = true
conf_limit = 1000
conf_per_structure = 100
rmsd_cutoff = 0.75 # in Angstrom
energy_cutoff = 10 # in kJ/mol

[conformer_search.executable]
schrodinger = "" # root folder for Schrodinger Suite (Maestro, MacroModel)
tinker = "" # root folder for tinker


[dft]
# uses Gaussian keywords as default
method = "gaussian" # accepts "gaussian", "nwchem", "orca"

charge = nan # leave as nan if charge is computed from SDFiles, set manualy otherwise
solvent = ""
n_basis_set = "6-311g(d)"  # Basis set for NMR calcs
n_functional = "mPW1PW91"  # Functional for NMR calcs
o_basis_set = "6-31g(d,p)"  # Basis set for geometry optimizations
o_functional = "b3lyp"  # Functional for geometry optimizations
e_basis_set = "def2tzvp"  # Basis set for energy calculations
e_functional = "m062x"  # Functional for energy calculations

optimisation_converged = false # force treatment of all DFT optimisations as converged
dft_complete = false # run if the calculations are complete

max_opt_cycles = 50
calc_force_constants = false
opt_step_size = 30 # 0.01N Bohr or radians.

num_processors = 1
memory = 2000 # memory in megabytes

c13_tms = 191.69255 
h1_tms = 31.7518583


[dft.executable]
nwchem = "nwchem"
gaussian = "g16"
orca = "orca"


[dft.cluster]

# set up passwordless connection first!
machine_name = ""
username = ""
time_limit = 24 # queue time limit, hours
queue = "" # SWAN on Ziggy
project = "" # project on hpc, not working with two-factor authentication
scratch_dir = ""
start_time = "" # set automatically

max_concurrent_jobs = 75 # 75 on Ziggy, 320 on Darwin

[nmr]

# B3LYP/6-31G** reference shielding
c13_tms = 191.69255 
h1_tms = 31.7518583

model = "g"
param_file = "none"


